Chocoworld-master/Chocoworld/Controllers/AccesoController.cs
using Microsoft.AspNetCore.Mvc;
using Chocoworld.Models;
using Chocoworld.Data;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.Eventing.Reader;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Chocoworld.Controllers
{
    // Constructor que recibe una instancia del contexto de la base de datos

    public class AccesoController : Controller
    {
        private readonly ChocomundoContext _context;
        public AccesoController(ChocomundoContext context)
        {
            _context = context;
        }
        // Método que devuelve la vista de inicio de sesión

        public IActionResult Login()
        {
            return View();
        }
        // Método para validar el usuario en la base de datos


        public Tuple<Cliente, Empleado> ValidarUsuario(string correo, string pass)
        {
            var cliente = _context.Clientes.FirstOrDefault(item => item.Email == correo && item.Contrasena == pass);
            var empleado = _context.Empleados.FirstOrDefault(item => item.Email == correo && item.Contrasena == pass);

            return new Tuple<Cliente, Empleado>(cliente, empleado);
        }
        // Método que maneja la autenticación cuando se envía el formulario de inicio de sesión

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel modelo)
        {
            string correo = modelo.CorreoElectronico;
            string pass = modelo.Contraseña;

            var validacion = ValidarUsuario(correo, pass);
            // Si el usuario es un cliente
            if (validacion.Item1 != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, validacion.Item1.Nombre + " " + validacion.Item1.Apellido),

                    new Claim("Correo", validacion.Item1.Email)
                };
                var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity));
                return RedirectToAction("Index", "Home");
            }
            // Si el usuario es un empleado
            else if (validacion.Item2 != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, validacion.Item2.Nombre + " " + validacion.Item2.Apellido),
                    new Claim("Correo", validacion.Item2.Email),
                    new Claim(ClaimTypes.Role, validacion.Item2.Rol)
                };
                var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity));

                return RedirectToAction("Index", "Dashboard");
                // Si la autenticación falla, regresa a la vista de inicio de sesión
            }
            else
            {
                return View();
            }
        }

        // Método para cerrar sesión
        public async Task<IActionResult> Cerrar()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClienteId,Nombre,Apellido,Email,Contrasena,ConfirmarContrasena,Telefono,DireccionId")] Cliente cliente)
        {
            bool redirectToHome = true; // Bandera para indicar si se debe redirigir a la página de inicio

            if (ModelState.IsValid)
            {
                if (cliente.Contrasena != cliente.ConfirmarContrasena)
                {
                    ModelState.AddModelError("ConfirmarContrasena", "La confirmación de la contraseña no coincide");
                    ViewData["DireccionId"] = new SelectList(_context.Direcciones, "DireccionId", "DireccionId", cliente.DireccionId);
                    redirectToHome = false; // No se redirige a la página de inicio si las contraseñas no coinciden
                }
                else
                {
                    // Hash the password before saving it to the database (ensure you have proper password hashing implementation)
                    // For example, you can use ASP.NET Core Identity UserManager to handle password hashing.
                    _context.Add(cliente);
                    await _context.SaveChangesAsync();

                    // Iniciar sesión automáticamente después del registro
                    var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, cliente.Nombre + " " + cliente.Apellido),
                new Claim("Correo", cliente.Email)
            };
                    var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity));

                    // La redirección se realizará después de un registro exitoso
                    return RedirectToAction("Index", "Home");
                }
            }

            // La redirección se realiza solo si redirectToHome es true
            if (redirectToHome)
            {
                ViewData["DireccionId"] = new SelectList(_context.Direcciones, "DireccionId", "DireccionId", cliente.DireccionId);
                return View(cliente);
            }

            return View();
        }

        

    }
}

Chocoworld-master/Chocoworld/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Chocoworld.Data;

namespace Chocoworld.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ChocomundoContext _context;

        public DashboardController(ChocomundoContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            int totalProductos = ObtenerTotalProductos();
            int totalClientes = ObtenerTotalClientes();
            int totalCategorias = ObtenerTotalCategorias();
            int totalEmpleados = ObtenerTotalEmpleados();


            ViewBag.TotalProductos = totalProductos;
            ViewBag.TotalClientes = totalClientes;
            ViewBag.TotalCategorias = totalCategorias;
            ViewBag.TotalEmpleados = totalEmpleados;


            return View();
        }

        private int ObtenerTotalProductos()
        {
            return _context.Productos.Count();
        }

        private int ObtenerTotalClientes()
        {
            return _context.Clientes.Count();
        }
        private int ObtenerTotalCategorias()
        {
            return _context.Categorias.Count();
        }
        private int ObtenerTotalEmpleados()
        {
            return _context.Empleados.Count();
        }


    }
}

Chocoworld-master/Chocoworld/Controllers/LotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Chocoworld.Data;
using Chocoworld.Models;

namespace Chocoworld.Controllers
{
    public class LotesController : Controller
    {
        private readonly ChocomundoContext _context;

        public LotesController(ChocomundoContext context)
        {
            _context = context;
        }

        // GET: Lotes
        public async Task<IActionResult> Index(string buscar)
        {
            var lotes = from lote in _context.Lotes select lote;
            if (!String.IsNullOrEmpty(buscar))
            {
                lotes = lotes.Where(lote => lote.Producto.Nombre.Contains(buscar));

            }   

            return View(await lotes.ToListAsync());
        }

        // GET: Lotes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Lotes == null)
            {
                return NotFound();
            }

            var lote = await _context.Lotes
                .Include(l => l.Producto)
                .FirstOrDefaultAsync(m => m.LoteId == id);
            if (lote == null)
            {
                return NotFound();
            }

            return View(lote);
        }

        // GET: Lotes/Create
        public IActionResult Create()
        {
            ViewData["ProductoId"] = new SelectList(_context.Productos, "ProductoId", "Nombre");
            return View();
        }

        // POST: Lotes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LoteId,ProductoId,FechaIngreso,FechaVencimiento,Cantidad,ProveedorId")] Lote lote)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lote);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductoId"] = new SelectList(_context.Productos, "ProductoId", "nombre", lote.ProductoId);
            return View(lote);
        }

        // GET: Lotes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Lotes == null)
            {
                return NotFound();
            }

            var lote = await _context.Lotes.FindAsync(id);
            if (lote == null)
            {
                return NotFound();
            }
            ViewData["ProductoId"] = new SelectList(_context.Productos, "ProductoId", "Nombre", lote.ProductoId);
            return View(lote);
        }

        // POST: Lotes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LoteId,ProductoId,FechaIngreso,FechaVencimiento,Cantidad,ProveedorId")] Lote lote)
        {
            if (id != lote.LoteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lote);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoteExists(lote.LoteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductoId"] = new SelectList(_context.Productos, "ProductoId", "ProductoId", lote.ProductoId);
            return View(lote);
        }

        // GET: Lotes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Lotes == null)
            {
                return NotFound();
            }

            var lote = await _context.Lotes
                .Include(l => l.Producto)
                .FirstOrDefaultAsync(m => m.LoteId == id);
            if (lote == null)
            {
                return NotFound();
            }

            return View(lote);
        }

        // POST: Lotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Lotes == null)
            {
                return Problem("Entity set 'ChocomundoContext.Lotes'  is null.");
            }
            var lote = await _context.Lotes.FindAsync(id);
            if (lote != null)
            {
                _context.Lotes.Remove(lote);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LoteExists(int id)
        {
          return (_context.Lotes?.Any(e => e.LoteId == id)).GetValueOrDefault();
        }
    }
}

Chocoworld-master/Chocoworld/Views/Shared/Dashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Chocoworld</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Chocoworld.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <!-- carrucel   -->
    <link rel="stylesheet" href="~/lib/owlcarousel/assets/owl.carousel.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Panel de Administración</a>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="position-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="">
                                Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="./crud/categorias/index.php">
                                Categorias
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="./crud/clientes/index.php">
                                Clientes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="./crud/direcciones/index.php">
                                Direcciones
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="./crud/empleados/index.php">
                                Empleados
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="./crud/lotes/index.php">
                                Lotes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="./crud/pedidos/index.php">
                                Pedidos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="./crud/productos/index.php">
                                Productos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="./crud/proveedores/index.php">
                                Proveedores
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
    <header>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Chocoworld - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Chocoworld-master/Chocoworld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Chocoworld</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Chocoworld.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <!-- carrucel   -->
    <link rel="stylesheet" href="~/lib/owlcarousel/assets/owl.carousel.min.css" asp-append-version="true" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Chocoworld</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Catalogo">Catalogo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Ubicacion">Ubicacion</a>
                        </li>
                        

                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <!-- Example single danger button -->
                            <div class="btn-group">
                                <button type="button" class="btn btn-success dropdown-toggle rounded-5" data-bs-toggle="dropdown" aria-expanded="false">
                                    bienvenido @User.Identity.Name
                                    <i class="fas fa-user fa-fw"></i>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user">
                                        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                        <circle cx="12" cy="7" r="4"></circle>
                                    </svg>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Perfil">Ver Perfil</a></li>
                                    <li><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Rdireccion">Registrar Direccion</a></li>
                                    <li><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Cambiarcontrasena">Cambiar contraseña</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="nav-link" asp-area="" asp-controller="Acceso" asp-action="Cerrar">Cerrar Sesión</a></li>
                                </ul>
                            </div>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Acceso" asp-action="Login">
                                    <button type="button" class="btn btn-secondary btn-success rounded-bottom">Iniciar Sesión</button>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script> 
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Chocoworld-master/Chocoworld/Views/Shared/_layout1.cshtml
@using Microsoft.AspNetCore.Identity;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Chocoworld</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Chocoworld.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <!-- carrucel   -->
    <link rel="stylesheet" href="~/lib/owlcarousel/assets/owl.carousel.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3 navbar navbar-dark bg-primary navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index">Panel de Administracion</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark btn bg-primary" asp-area="" asp-controller="Dashboard" asp-action="Index">Panel de Control</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedidoes" asp-action="Index">Pedidos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Direcciones" asp-action="Index">Direcciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleadoes" asp-action="Index">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Imagenes" asp-action="Index">Imagenes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lotes" asp-action="Index">Lotes</a>
                        </li>

                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Acceso" asp-action="Cerrar">
                                    <button type="button" class="btn btn-secondary rounded">Cerrar Sesión</button>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Acceso" asp-action="Login">
                                    <button type="button" class="btn btn-secondary rounded">Iniciar Sesión</button>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script> 
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>