Chocoworld-master/Chocoworld/Models/Producto.cs
using System;
using System.Collections.Generic;

namespace Chocoworld.Models;

public partial class Producto
{
    public int ProductoId { get; set; }

    public string? Nombre { get; set; }

    public string? Descripcion { get; set; }

    public decimal? Precio { get; set; }

    public int? CategoriaId { get; set; }

    public virtual ICollection<Carritodecompra> Carritodecompras { get; set; } = new List<Carritodecompra>();

    public virtual Categoria? Categoria { get; set; }

    public virtual ICollection<Comentariosproducto> Comentariosproductos { get; set; } = new List<Comentariosproducto>();

    public virtual ICollection<Detallespedido> Detallespedidos { get; set; } = new List<Detallespedido>();

    public virtual ICollection<Imagene> Imagenes { get; set; } = new List<Imagene>();

    public virtual ICollection<Lote> Lotes { get; set; } = new List<Lote>();
}

Chocoworld-master/Chocoworld/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Chocoworld.Data;
using Chocoworld.Models;
using Microsoft.AspNetCore.Authorization;

namespace Chocoworld.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ChocomundoContext _context;

        public ProductoController(ChocomundoContext context)
        {
            _context = context;
        }

        // GET: Producto
        public async Task<IActionResult> Index(string buscar)
        {
            var productos = from producto in _context.Productos select producto;
            if (!String.IsNullOrEmpty(buscar))
            {
                productos = productos.Where(producto => producto.Nombre.Contains(buscar));
            }
            return View(await productos.ToListAsync());
        }

        // GET: Producto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Producto/Create
        public IActionResult Create()
        {
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "CategoriaId", "Nombre");
            return View();
        }

        // POST: Producto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductoId,Nombre,Descripcion,Precio,CategoriaId")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "CategoriaId", "Nombre", producto.CategoriaId);
            return View(producto);
        }

        // GET: Producto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "CategoriaId", "Nombre", producto.CategoriaId);
            return View(producto);
        }

        // POST: Producto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductoId,Nombre,Descripcion,Precio,Nombre")] Producto producto)
        {
            if (id != producto.ProductoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.ProductoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "CategoriaId", "Nombre", producto.CategoriaId);
            return View(producto);
        }

        // GET: Producto/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        [Authorize(Roles = "Administrador")]
        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Productos == null)
            {
                return Problem("Entity set 'ChocomundoContext.Productos'  is null.");
            }
            var producto = await _context.Productos.FindAsync(id);
            if (producto != null)
            {
                _context.Productos.Remove(producto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
          return (_context.Productos?.Any(e => e.ProductoId == id)).GetValueOrDefault();
        }
    }
}

Chocoworld-master/Chocoworld/Views/Producto/Create.cshtml
@model Chocoworld.Models.Producto

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_layout1.cshtml";
}

<h1>Crear </h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoriaId" class="control-label">Nombre Categoria</label>
                <select asp-for="CategoriaId" class ="form-control" asp-items="ViewBag.CategoriaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary rounded" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-success rounded">Volver al listado</a>
</div>

Chocoworld-master/Chocoworld/Views/Producto/Delete.cshtml
@model Chocoworld.Models.Producto

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_layout1.cshtml";
}

<h1>Eliminar Producto</h1>

<h3>Esta seguro que quiere eliminar este producto?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria.CategoriaId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductoId" />
        <input type="submit" value="Eliminar" class="btn btn-danger rounded"/> 
        <a asp-action="Index" class="btn btn-success rounded">Volver al listado</a>
    </form>
</div>

Chocoworld-master/Chocoworld/Views/Producto/Details.cshtml
@model Chocoworld.Models.Producto

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_layout1.cshtml";
}

<h1>Detalles de producto</h1>

<div>
    <h4>Productos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria.CategoriaId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-warning rounded" asp-route-id="@Model?.ProductoId">Editar</a> 
    <a asp-action="Index" class="btn btn-success rounded">Volver al listado</a>
</div>

Chocoworld-master/Chocoworld/Views/Producto/Edit.cshtml
@model Chocoworld.Models.Producto

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_layout1.cshtml";
}

<h1>Editar Producto</h1>

<h4>Productos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductoId" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoriaId" class="control-label"></label>
                <select asp-for="CategoriaId" class="form-control" asp-items="ViewBag.CategoriaId"></select>
                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary rounded" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-success rounded">Volver al listado</a>
</div>

Chocoworld-master/Chocoworld/Views/Producto/Index.cshtml
@model IEnumerable<Chocoworld.Models.Producto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_layout1.cshtml";

}


<h1>Productos</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Crear Producto</a>
</p>
<form asp-controller="Producto" asp-action="Index">
    <p>
        <label class="form-label" for="form1">Buscar</label>
        <input type="search" id="form1" name="buscar" class="form-control" />
        <input type="submit" value="Buscar" class="btn btn-primary m-1" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoriaId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoriaId)
            </td>
            <td>
                    <a asp-action="Edit" class="btn btn-primary rounded" asp-route-id="@item.ProductoId">Editar</a>
                    <a asp-action="Details" class="btn btn-warning rounded" asp-route-id="@item.ProductoId">Detalles</a>
                    @if (User.IsInRole("Administrador"))
                    {
                        <a asp-action="Delete" class="btn btn-danger rounded" asp-route-id="@item.ProductoId">Eliminar</a>
                    }
                </td>
        </tr>
}
    </tbody>
</table>